// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClgWOV1oSVGKIWcMof-81wpssOzm1dHos',
    appId: '1:361270705896:web:14ea19b64cd85201ed135d',
    messagingSenderId: '361270705896',
    projectId: 'flutter-fire-codelab-6d8d8',
    authDomain: 'flutter-fire-codelab-6d8d8.firebaseapp.com',
    databaseURL: 'https://flutter-fire-codelab-6d8d8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-fire-codelab-6d8d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7pJ5dDa019-27GzPQ_ujuQRnsl-fEtYs',
    appId: '1:361270705896:android:b73bd34a2138ec9bed135d',
    messagingSenderId: '361270705896',
    projectId: 'flutter-fire-codelab-6d8d8',
    databaseURL: 'https://flutter-fire-codelab-6d8d8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-fire-codelab-6d8d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfGdqXqnV_UzW4qFfRWZJOlXnApRnEFNY',
    appId: '1:361270705896:ios:664da0c009d2ee0eed135d',
    messagingSenderId: '361270705896',
    projectId: 'flutter-fire-codelab-6d8d8',
    databaseURL: 'https://flutter-fire-codelab-6d8d8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-fire-codelab-6d8d8.appspot.com',
    iosClientId: '361270705896-k239ecgcjob3hlv9s61jpsv5ef2qrar0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfGdqXqnV_UzW4qFfRWZJOlXnApRnEFNY',
    appId: '1:361270705896:ios:664da0c009d2ee0eed135d',
    messagingSenderId: '361270705896',
    projectId: 'flutter-fire-codelab-6d8d8',
    databaseURL: 'https://flutter-fire-codelab-6d8d8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-fire-codelab-6d8d8.appspot.com',
    iosClientId: '361270705896-k239ecgcjob3hlv9s61jpsv5ef2qrar0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
